### PR TITLE
Update to Docusaurus v2

### LINKED ISSUE #186: Update to Docusaurus v2
Now Docusaurus v2 beta is available! 🎉 
https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta

This new version should fix vulnerable npm dependencies.

### PR DESCRIPTION
**Pull request by ybiquitous**
Migration guide: https://docusaurus.io/docs/migration

Close #186

## Usage

You can view the website on your localhost:

1. Checkout the `issue-186` branch 
2. Run `npm install && npm start`

## Notes

- Stop publishing versioned pages to ensure our maintainability.

## Checklist

- [x] Add necessary files to `website/`
- [x] Remove `docusaurus/`
- [x] Update "Development" section on README
  - https://github.com/sider/goodcheck/blob/0a6c9b38ba9f58956686e9d0dcdae20c95fe1aa1/README.md#development

## Screenshot

image

image

### CODE REVIEW

**Comment by dev-yakuza** [comment]
@ybiquitous 
Brand and nav links that are always `white` look good to me. what do you think? 🤔 

| Current | White |
| -- | -- |
| Screen Shot 2021-09-02 at 17 00 37 | Screen Shot 2021-09-02 at 16 59 28 |

**Comment by dev-yakuza** [comment]
[Question]
is there a meaning of the `italic` title on [this page](http://localhost:3000/goodcheck/docs/configuration#pattern)? (`string literal` is not italic, but other titles are italic)

([Current page](https://sider.github.io/goodcheck/docs/configuration#pattern) is also the `italic` so it's not a problem of this PR.)

| Current | New |
| -- | -- |
| Screen Shot 2021-09-02 at 17 09 44 | Screen Shot 2021-09-02 at 17 08 40 |

**Comment by ybiquitous** [comment]
> Brand and nav links that are always `white` look good to me. what do you think? 🤔

I also think so. How about 189163f?

**Comment by ybiquitous** [comment]
> is there a meaning of the `italic` title on [this page](http://localhost:3000/goodcheck/docs/configuration#pattern)? (`string literal` is not italic, but other titles are italic)
> 
> ([Current page](https://sider.github.io/goodcheck/docs/configuration#pattern) is also the `italic` so it's not a problem of this PR.)

I also think it's weird. 😅 
I'll fix the headings style with another PR. 💪🏼

**Review by dev-yakuza — APPROVED** [review]
Lovely ❤️ 
Thanks for your works 🙇‍♂️

**Comment by ybiquitous** [comment]
@dev-yakuza Thank you for the review! 😄

**Pull request merged**
