### PR TITLE
Fix the pattern of disable lines for Slash-asterisk and add support for JSX

### LINKED ISSUE #130: Unable to disable line or next line check in JSX
I'm unable to get disable line comments working in JSX.  The only form of comments allowed are [`{/* */}`](https://reactjs.org/docs/faq-build.html#how-can-i-write-comments-in-jsx), so I've tried both:

```js
<p>problematic line</p> {/* goodcheck-disable-line */}
```

and 

```js
{/* goodcheck-disable-next-line */}
<p>problematic line</p> 
```

and even

```js
{/* // goodcheck-disable-next-line */}
<p>problematic line</p> 
```

for good measure but my goodcheck linter (run via `goodcheck check`) is still flagging the problem lines in all cases.

Is there an alternate syntax that will work for JSX or can the checker be adjusted to accommodate this?

### PR DESCRIPTION
**Pull request by yykamei**
The asterisk of the pattern of Slash-asterisk style comments should be escaped with back-slash. In addition to fixing the character, comments in JSX could not be detected, so I added a new pattern for JSX: `{/* goodcheck-disable-line */}` and `{/* goodcheck-disable-next-line */}`.

Fix #130

### CODE REVIEW

**Review by ybiquitous — COMMENTED** [review]
Can you add a test case for JSX comment pattern `{/* */}`?

**Comment by yykamei** [comment]
I added and I confirmed this test failed.

**Comment by yykamei** [comment]
How should I fix it? @ybiquitous

**Comment by ybiquitous** [comment]
How about adding the new patterns? 👇 

```
/\{\/\* goodcheck-disable-line \*\/\}$/

/\{\/\* goodcheck-disable-next-line \*\/\}$/
```

**Comment by yykamei** [comment]
I added via c938e3c. Thank you.

I'm tweaking the previous commit because I think the pattern with white-space could be possible like `{ /* ... */ }`.

**Comment by ybiquitous** [comment]
Looks nice. 👍 

I think this pull request has fixed a bug for CSS and added new support for JSX, so it seems good to change the pull request's title.

**Review by ybiquitous — APPROVED** [review]
Lgtm 👏

**Comment by yykamei** [comment]
Thanks. I rewrote the title. I didn't come up with adding a new pattern. I appreciate your quick response :pray:

**Comment by yykamei** [comment]
I accidentally merged without squashing..

**Pull request merged**
